Up sampling
down sampling

In [19]:
# 🔹 Without a fixed seed → every run gives different random values

# 🔹 With the same seed → every run gives the same sequence of random values
import random

random.seed(20)
print(random.random())
print(random.random())

0.9056396761745207
0.6862541570267026

In [20]:
import pandas as pd 
import numpy as np
n_sample = 1000
class_ratio_0 = .9
n_class_0 = int(n_sample * class_ratio_0)
n_class_1 = n_sample - n_class_0

In [21]:
n_class_0,n_class_1

(900, 100)

### CREATE MY DATAFRAME WITH IMBALANCED DATASET

In [22]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0,class_1]).reset_index(drop = True)

#### It creates n_class_0 random numbers drawn from a normal distribution with mean = 0 and standard deviation = 1, and assigns them to a feature called feature_1

In [23]:
df.head()

   feature_1  feature_2  target
0   1.164336  -0.829219       0
1  -0.341551  -0.664289       0
2  -0.027846   0.306929       0
3   0.954641   0.728017       0
4   1.386644  -0.233561       0

In [24]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

### UP_sampling

In [25]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

Resampling for imbalanced data (ML)

Goal: help model learn minority class

How it works:

Oversampling: duplicate or synthesize minority samples

Undersampling: remove majority samples

In [26]:
from sklearn.utils import resample

df_minority_upsampled = resample(df_minority, replace = True,
         n_samples = len(df_majority),
         random_state = 42 # fixed seed
           )

In [27]:
df_minority_upsampled.shape

(900, 3)

In [28]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.974171   0.377546       1
992   3.290031   1.132033       1
914   2.792659   1.610208       1
971   2.670899   0.869572       1
960   0.983812   2.532996       1

In [29]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [30]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### Down_Sampling --Bad for losing data

In [31]:
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0,class_1]).reset_index(drop = True)

In [32]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [33]:
from sklearn.utils import resample

df_majority_downsampled = resample(df_majority, replace = False,
         n_samples = len(df_minority),
         random_state = 42 # fixed seed
           )

In [34]:
df_majority_downsampled.shape

(100, 3)

In [35]:
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

In [36]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64