In [163]:
import pandas as pd
df = pd.read_csv('tips.csv')

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [165]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

# Label Encoding one hot Encoding

In [166]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [167]:
x = df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y = df['total_bill']

In [168]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 42)

In [169]:
x_train.head()

      tip     sex smoker  day    time  size
115  3.50  Female     No  Sun  Dinner     2
181  5.65    Male    Yes  Sun  Dinner     2
225  2.50  Female    Yes  Fri   Lunch     2
68   2.01    Male     No  Sat  Dinner     2
104  4.08  Female     No  Sat  Dinner     2

👉 Train = fit_transform()
👉 Test / New = transform()

In [170]:
# Label Encoder 

from sklearn.preprocessing import LabelEncoder
l1 = LabelEncoder()
l2 = LabelEncoder()
l3 = LabelEncoder()

x_train['sex'] = l1.fit_transform(x_train['sex'])
x_train['smoker'] = l2.fit_transform(x_train['smoker'])
x_train['time'] = l3.fit_transform(x_train['time'])

In [171]:
x_train.head()

      tip  sex  smoker  day  time  size
115  3.50    0       0  Sun     0     2
181  5.65    1       1  Sun     0     2
225  2.50    0       1  Fri     1     2
68   2.01    1       0  Sat     0     2
104  4.08    0       0  Sat     0     2

In [172]:
x_test['sex'] = l1.transform(x_test['sex'])
x_test['smoker'] = l2.transform(x_test['smoker'])
x_test['time'] = l3.transform(x_test['time'])

In [173]:
x_test.head()

      tip  sex  smoker   day  time  size
24   3.18    1       0   Sat     0     2
6    2.00    1       0   Sun     0     2
153  2.00    1       0   Sun     0     4
211  5.16    1       1   Sat     0     4
198  2.00    0       1  Thur     1     2

In [174]:
# OneHot encoding - ColumnTransformer 

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# “Take column 3 → convert categorical values into numeric using one-hot encoding (dropping first column), and keep all other columns as they are.
ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(drop = 'first'),[3])], remainder='passthrough')

In [175]:
x_train = ct.fit_transform(x_train)
x_train

array([[0., 1., 0., ..., 0., 0., 2.],
       [0., 1., 0., ..., 1., 0., 2.],
       [0., 0., 0., ..., 1., 1., 2.],
       ...,
       [0., 0., 0., ..., 1., 0., 2.],
       [0., 1., 0., ..., 1., 0., 2.],
       [1., 0., 0., ..., 1., 0., 3.]], shape=(183, 8))

In [176]:
x_test = ct.transform(x_test)
x_test

array([[1.  , 0.  , 0.  , 3.18, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 5.16, 1.  , 1.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 1.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.56, 1.  , 1.  , 1.  , 2.  ],
       [0.  , 0.  , 1.  , 2.52, 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.23, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 3.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.  , 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.47, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.5 , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 1.83, 0.  , 0.  , 1.  , 1.  ],
       [0.  , 0.  , 1.  , 1.36, 0.  , 0.  , 1.  , 3.  ],
       [0.  , 0.  , 1.  , 4.  , 1.  , 1.  , 1.  , 3.  ],
       [0.  , 1.  , 0.  , 3.92, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.47, 0.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 1.  , 0.  , 1.  , 5.  ],
       [1.  , 0.  , 0.  , 2.45, 0.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.35, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 4.  , 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.45, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 1.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.31, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 1.71, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 5.  , 0.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.  , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 1.  , 0.  , 5.  , 1.  , 0.  , 0.  , 6.  ],
       [0.  , 1.  , 0.  , 4.  , 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 1.44, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.34, 1.  , 0.  , 0.  , 4.  ],
       [1.  , 0.  , 0.  , 3.21, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 3.5 , 0.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.92, 0.  , 0.  , 1.  , 4.  ],
       [0.  , 0.  , 0.  , 1.5 , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 5.  , 0.  , 1.  , 1.  , 4.  ],
       [0.  , 0.  , 1.  , 2.75, 0.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.  , 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.25, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 0.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 2.55, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 1.67, 0.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 1.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 1.  , 0.  , 1.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  , 1.61, 0.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.31, 1.  , 0.  , 0.  , 3.  ],
       [0.  , 0.  , 1.  , 1.44, 1.  , 0.  , 1.  , 2.  ],
       [1.  , 0.  , 0.  , 2.72, 1.  , 0.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 2.03, 1.  , 1.  , 0.  , 2.  ],
       [0.  , 0.  , 0.  , 4.  , 1.  , 1.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 4.5 , 1.  , 0.  , 0.  , 4.  ],
       [0.  , 0.  , 1.  , 2.03, 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 3.51, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 0.  , 1.  , 2.  , 1.  , 0.  , 1.  , 2.  ],
       [0.  , 1.  , 0.  , 5.15, 1.  , 1.  , 0.  , 2.  ],
       [1.  , 0.  , 0.  , 1.75, 1.  , 0.  , 0.  , 2.  ],
       [0.  , 1.  , 0.  , 2.74, 1.  , 0.  , 0.  , 3.  ],
       [1.  , 0.  , 0.  , 3.  , 1.  , 1.  , 0.  , 3.  ],
       [0.  , 1.  , 0.  , 5.14, 0.  , 0.  , 0.  , 5.  ]])

In [177]:
from sklearn.svm import SVR
svr = SVR()

In [178]:
svr.fit(x_train,y_train)

SVR()

In [179]:
y_pred = svr.predict(x_test)

In [180]:
from sklearn.metrics import r2_score, mean_absolute_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.49798620106004743
4.463296539661224

# Hyper parameter tuning

In [181]:
from sklearn.model_selection import GridSearchCV
params = {
	"C": [100, 10, 1.0, 0.1, 0.01],
	"kernel": ["linear", "rbf", "poly", "sigmoid"],
	"gamma": ["scale", "auto"]
}

grid = GridSearchCV(SVR(), param_grid=params, refit=True, cv=5, verbose=3)

In [182]:
grid.fit(x_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits
[CV 1/5] END .C=100, gamma=scale, kernel=linear;, score=0.667 total time=   0.0s
[CV 2/5] END .C=100, gamma=scale, kernel=linear;, score=0.664 total time=   0.0s
[CV 3/5] END .C=100, gamma=scale, kernel=linear;, score=0.361 total time=   0.0s
[CV 4/5] END .C=100, gamma=scale, kernel=linear;, score=0.674 total time=   0.0s
[CV 5/5] END .C=100, gamma=scale, kernel=linear;, score=0.199 total time=   0.0s
[CV 1/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.435 total time=   0.0s
[CV 2/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.711 total time=   0.0s
[CV 3/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.435 total time=   0.0s
[CV 4/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.528 total time=   0.0s
[CV 5/5] END ....C=100, gamma=scale, kernel=rbf;, score=0.256 total time=   0.0s
[CV 1/5] END ...C=100, gamma=scale, kernel=poly;, score=0.353 total time=   0.0s
[CV 2/5] END ..C=100, gamma=scale, kernel=poly;, score=-0.077 total time=   0.0s
[CV 3/5] END ..C=100, gamma=scale, kernel=poly;, score=-0.001 total time=   0.0s
[CV 4/5] END ...C=100, gamma=scale, kernel=poly;, score=0.556 total time=   0.0s
[CV 5/5] END ...C=100, gamma=scale, kernel=poly;, score=0.135 total time=   0.0s
[CV 1/5] END C=100, gamma=scale, kernel=sigmoid;, score=-1917.386 total time=   0.0s
[CV 2/5] END C=100, gamma=scale, kernel=sigmoid;, score=-1751.298 total time=   0.0s
[CV 3/5] END C=100, gamma=scale, kernel=sigmoid;, score=-1384.394 total time=   0.0s
[CV 4/5] END C=100, gamma=scale, kernel=sigmoid;, score=-1335.244 total time=   0.0s
[CV 5/5] END C=100, gamma=scale, kernel=sigmoid;, score=-1267.036 total time=   0.0s
[CV 1/5] END ..C=100, gamma=auto, kernel=linear;, score=0.667 total time=   0.0s
[CV 2/5] END ..C=100, gamma=auto, kernel=linear;, score=0.664 total time=   0.0s
[CV 3/5] END ..C=100, gamma=auto, kernel=linear;, score=0.361 total time=   0.0s
[CV 4/5] END ..C=100, gamma=auto, kernel=linear;, score=0.674 total time=   0.0s
[CV 5/5] END ..C=100, gamma=auto, kernel=linear;, score=0.199 total time=   0.0s
[CV 1/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.242 total time=   0.0s
[CV 2/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.699 total time=   0.0s
[CV 3/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.402 total time=   0.0s
[CV 4/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.341 total time=   0.0s
[CV 5/5] END .....C=100, gamma=auto, kernel=rbf;, score=0.328 total time=   0.0s
[CV 1/5] END ....C=100, gamma=auto, kernel=poly;, score=0.099 total time=   0.0s
[CV 2/5] END ...C=100, gamma=auto, kernel=poly;, score=-1.020 total time=   0.0s
[CV 3/5] END ....C=100, gamma=auto, kernel=poly;, score=0.117 total time=   0.0s
[CV 4/5] END ....C=100, gamma=auto, kernel=poly;, score=0.493 total time=   0.0s
[CV 5/5] END ...C=100, gamma=auto, kernel=poly;, score=-0.058 total time=   0.0s
[CV 1/5] END C=100, gamma=auto, kernel=sigmoid;, score=-1983.723 total time=   0.0s
[CV 2/5] END C=100, gamma=auto, kernel=sigmoid;, score=-1629.352 total time=   0.0s
[CV 3/5] END C=100, gamma=auto, kernel=sigmoid;, score=-1305.525 total time=   0.0s
[CV 4/5] END C=100, gamma=auto, kernel=sigmoid;, score=-1515.715 total time=   0.0s
[CV 5/5] END C=100, gamma=auto, kernel=sigmoid;, score=-1777.001 total time=   0.0s
[CV 1/5] END ..C=10, gamma=scale, kernel=linear;, score=0.667 total time=   0.0s
[CV 2/5] END ..C=10, gamma=scale, kernel=linear;, score=0.664 total time=   0.0s
[CV 3/5] END ..C=10, gamma=scale, kernel=linear;, score=0.364 total time=   0.0s
[CV 4/5] END ..C=10, gamma=scale, kernel=linear;, score=0.674 total time=   0.0s
[CV 5/5] END ..C=10, gamma=scale, kernel=linear;, score=0.208 total time=   0.0s
[CV 1/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.620 total time=   0.0s
[CV 2/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.640 total time=   0.0s
[CV 3/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.414 total time=   0.0s
[CV 4/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.613 total time=   0.0s
[CV 5/5] END .....C=10, gamma=scale, kernel=rbf;, score=0.233 total time=   0.0s
[CV 1/5] END ....C=10, gamma=scale, kernel=poly;, score=0.497 total time=   0.0s
[CV 2/5] END ....C=10, gamma=scale, kernel=poly;, score=0.483 total time=   0.0s
[CV 3/5] END ....C=10, gamma=scale, kernel=poly;, score=0.153 total time=   0.0s
[CV 4/5] END ....C=10, gamma=scale, kernel=poly;, score=0.632 total time=   0.0s
[CV 5/5] END ....C=10, gamma=scale, kernel=poly;, score=0.252 total time=   0.0s
[CV 1/5] END C=10, gamma=scale, kernel=sigmoid;, score=-23.579 total time=   0.0s
[CV 2/5] END C=10, gamma=scale, kernel=sigmoid;, score=-22.290 total time=   0.0s
[CV 3/5] END C=10, gamma=scale, kernel=sigmoid;, score=-18.050 total time=   0.0s
[CV 4/5] END C=10, gamma=scale, kernel=sigmoid;, score=-18.190 total time=   0.0s
[CV 5/5] END C=10, gamma=scale, kernel=sigmoid;, score=-16.009 total time=   0.0s
[CV 1/5] END ...C=10, gamma=auto, kernel=linear;, score=0.667 total time=   0.0s
[CV 2/5] END ...C=10, gamma=auto, kernel=linear;, score=0.664 total time=   0.0s
[CV 3/5] END ...C=10, gamma=auto, kernel=linear;, score=0.364 total time=   0.0s
[CV 4/5] END ...C=10, gamma=auto, kernel=linear;, score=0.674 total time=   0.0s
[CV 5/5] END ...C=10, gamma=auto, kernel=linear;, score=0.208 total time=   0.0s
[CV 1/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.557 total time=   0.0s
[CV 2/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.625 total time=   0.0s
[CV 3/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.430 total time=   0.0s
[CV 4/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.567 total time=   0.0s
[CV 5/5] END ......C=10, gamma=auto, kernel=rbf;, score=0.257 total time=   0.0s
[CV 1/5] END .....C=10, gamma=auto, kernel=poly;, score=0.391 total time=   0.0s
[CV 2/5] END .....C=10, gamma=auto, kernel=poly;, score=0.220 total time=   0.0s
[CV 3/5] END .....C=10, gamma=auto, kernel=poly;, score=0.048 total time=   0.0s
[CV 4/5] END .....C=10, gamma=auto, kernel=poly;, score=0.583 total time=   0.0s
[CV 5/5] END .....C=10, gamma=auto, kernel=poly;, score=0.160 total time=   0.0s
[CV 1/5] END C=10, gamma=auto, kernel=sigmoid;, score=-26.373 total time=   0.0s
[CV 2/5] END C=10, gamma=auto, kernel=sigmoid;, score=-21.444 total time=   0.0s
[CV 3/5] END C=10, gamma=auto, kernel=sigmoid;, score=-17.013 total time=   0.0s
[CV 4/5] END C=10, gamma=auto, kernel=sigmoid;, score=-19.802 total time=   0.0s
[CV 5/5] END C=10, gamma=auto, kernel=sigmoid;, score=-21.955 total time=   0.0s
[CV 1/5] END .C=1.0, gamma=scale, kernel=linear;, score=0.618 total time=   0.0s
[CV 2/5] END .C=1.0, gamma=scale, kernel=linear;, score=0.664 total time=   0.0s
[CV 3/5] END .C=1.0, gamma=scale, kernel=linear;, score=0.371 total time=   0.0s
[CV 4/5] END .C=1.0, gamma=scale, kernel=linear;, score=0.671 total time=   0.0s
[CV 5/5] END .C=1.0, gamma=scale, kernel=linear;, score=0.221 total time=   0.0s
[CV 1/5] END ....C=1.0, gamma=scale, kernel=rbf;, score=0.491 total time=   0.0s
[CV 2/5] END ....C=1.0, gamma=scale, kernel=rbf;, score=0.477 total time=   0.0s
[CV 3/5] END ....C=1.0, gamma=scale, kernel=rbf;, score=0.341 total time=   0.0s
[CV 4/5] END ....C=1.0, gamma=scale, kernel=rbf;, score=0.443 total time=   0.0s
[CV 5/5] END ....C=1.0, gamma=scale, kernel=rbf;, score=0.199 total time=   0.0s
[CV 1/5] END ...C=1.0, gamma=scale, kernel=poly;, score=0.409 total time=   0.0s
[CV 2/5] END ...C=1.0, gamma=scale, kernel=poly;, score=0.543 total time=   0.0s
[CV 3/5] END ...C=1.0, gamma=scale, kernel=poly;, score=0.227 total time=   0.0s
[CV 4/5] END ...C=1.0, gamma=scale, kernel=poly;, score=0.652 total time=   0.0s
[CV 5/5] END ...C=1.0, gamma=scale, kernel=poly;, score=0.218 total time=   0.0s
[CV 1/5] END C=1.0, gamma=scale, kernel=sigmoid;, score=-0.854 total time=   0.0s
[CV 2/5] END C=1.0, gamma=scale, kernel=sigmoid;, score=-0.699 total time=   0.0s
[CV 3/5] END C=1.0, gamma=scale, kernel=sigmoid;, score=-0.500 total time=   0.0s
[CV 4/5] END C=1.0, gamma=scale, kernel=sigmoid;, score=-0.651 total time=   0.0s
[CV 5/5] END C=1.0, gamma=scale, kernel=sigmoid;, score=-0.586 total time=   0.0s
[CV 1/5] END ..C=1.0, gamma=auto, kernel=linear;, score=0.618 total time=   0.0s
[CV 2/5] END ..C=1.0, gamma=auto, kernel=linear;, score=0.664 total time=   0.0s
[CV 3/5] END ..C=1.0, gamma=auto, kernel=linear;, score=0.371 total time=   0.0s
[CV 4/5] END ..C=1.0, gamma=auto, kernel=linear;, score=0.671 total time=   0.0s
[CV 5/5] END ..C=1.0, gamma=auto, kernel=linear;, score=0.221 total time=   0.0s
[CV 1/5] END .....C=1.0, gamma=auto, kernel=rbf;, score=0.494 total time=   0.0s
[CV 2/5] END .....C=1.0, gamma=auto, kernel=rbf;, score=0.456 total time=   0.0s
[CV 3/5] END .....C=1.0, gamma=auto, kernel=rbf;, score=0.327 total time=   0.0s
[CV 4/5] END .....C=1.0, gamma=auto, kernel=rbf;, score=0.405 total time=   0.0s
[CV 5/5] END .....C=1.0, gamma=auto, kernel=rbf;, score=0.200 total time=   0.0s
[CV 1/5] END ....C=1.0, gamma=auto, kernel=poly;, score=0.492 total time=   0.0s
[CV 2/5] END ....C=1.0, gamma=auto, kernel=poly;, score=0.530 total time=   0.0s
[CV 3/5] END ....C=1.0, gamma=auto, kernel=poly;, score=0.204 total time=   0.0s
[CV 4/5] END ....C=1.0, gamma=auto, kernel=poly;, score=0.650 total time=   0.0s
[CV 5/5] END ....C=1.0, gamma=auto, kernel=poly;, score=0.260 total time=   0.0s
[CV 1/5] END C=1.0, gamma=auto, kernel=sigmoid;, score=-0.893 total time=   0.0s
[CV 2/5] END C=1.0, gamma=auto, kernel=sigmoid;, score=-0.654 total time=   0.0s
[CV 3/5] END C=1.0, gamma=auto, kernel=sigmoid;, score=-0.511 total time=   0.0s
[CV 4/5] END C=1.0, gamma=auto, kernel=sigmoid;, score=-0.626 total time=   0.0s
[CV 5/5] END C=1.0, gamma=auto, kernel=sigmoid;, score=-0.683 total time=   0.0s
[CV 1/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.502 total time=   0.0s
[CV 2/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.650 total time=   0.0s
[CV 3/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.383 total time=   0.0s
[CV 4/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.635 total time=   0.0s
[CV 5/5] END .C=0.1, gamma=scale, kernel=linear;, score=0.202 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.014 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.093 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.077 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=scale, kernel=rbf;, score=0.103 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=scale, kernel=rbf;, score=-0.026 total time=   0.0s
[CV 1/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.342 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.581 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.277 total time=   0.0s
[CV 4/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.649 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=scale, kernel=poly;, score=0.152 total time=   0.0s
[CV 1/5] END C=0.1, gamma=scale, kernel=sigmoid;, score=-0.218 total time=   0.0s
[CV 2/5] END C=0.1, gamma=scale, kernel=sigmoid;, score=-0.083 total time=   0.0s
[CV 3/5] END C=0.1, gamma=scale, kernel=sigmoid;, score=-0.064 total time=   0.0s
[CV 4/5] END C=0.1, gamma=scale, kernel=sigmoid;, score=-0.089 total time=   0.0s
[CV 5/5] END C=0.1, gamma=scale, kernel=sigmoid;, score=-0.205 total time=   0.0s
[CV 1/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.502 total time=   0.0s
[CV 2/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.650 total time=   0.0s
[CV 3/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.383 total time=   0.0s
[CV 4/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.635 total time=   0.0s
[CV 5/5] END ..C=0.1, gamma=auto, kernel=linear;, score=0.202 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=auto, kernel=rbf;, score=0.019 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=auto, kernel=rbf;, score=0.093 total time=   0.0s
[CV 3/5] END .....C=0.1, gamma=auto, kernel=rbf;, score=0.077 total time=   0.0s
[CV 4/5] END .....C=0.1, gamma=auto, kernel=rbf;, score=0.095 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=auto, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.363 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.547 total time=   0.0s
[CV 3/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.182 total time=   0.0s
[CV 4/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.649 total time=   0.0s
[CV 5/5] END ....C=0.1, gamma=auto, kernel=poly;, score=0.194 total time=   0.0s
[CV 1/5] END C=0.1, gamma=auto, kernel=sigmoid;, score=-0.218 total time=   0.0s
[CV 2/5] END C=0.1, gamma=auto, kernel=sigmoid;, score=-0.076 total time=   0.0s
[CV 3/5] END C=0.1, gamma=auto, kernel=sigmoid;, score=-0.061 total time=   0.0s
[CV 4/5] END C=0.1, gamma=auto, kernel=sigmoid;, score=-0.080 total time=   0.0s
[CV 5/5] END C=0.1, gamma=auto, kernel=sigmoid;, score=-0.210 total time=   0.0s
[CV 1/5] END C=0.01, gamma=scale, kernel=linear;, score=0.079 total time=   0.0s
[CV 2/5] END C=0.01, gamma=scale, kernel=linear;, score=0.262 total time=   0.0s
[CV 3/5] END C=0.01, gamma=scale, kernel=linear;, score=0.177 total time=   0.0s
[CV 4/5] END C=0.01, gamma=scale, kernel=linear;, score=0.277 total time=   0.0s
[CV 5/5] END C=0.01, gamma=scale, kernel=linear;, score=0.020 total time=   0.0s
[CV 1/5] END ..C=0.01, gamma=scale, kernel=rbf;, score=-0.139 total time=   0.0s
[CV 2/5] END ..C=0.01, gamma=scale, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 3/5] END ..C=0.01, gamma=scale, kernel=rbf;, score=-0.021 total time=   0.0s
[CV 4/5] END ..C=0.01, gamma=scale, kernel=rbf;, score=-0.021 total time=   0.0s
[CV 5/5] END ..C=0.01, gamma=scale, kernel=rbf;, score=-0.148 total time=   0.0s
[CV 1/5] END ..C=0.01, gamma=scale, kernel=poly;, score=0.165 total time=   0.0s
[CV 2/5] END ..C=0.01, gamma=scale, kernel=poly;, score=0.535 total time=   0.0s
[CV 3/5] END ..C=0.01, gamma=scale, kernel=poly;, score=0.302 total time=   0.0s
[CV 4/5] END ..C=0.01, gamma=scale, kernel=poly;, score=0.535 total time=   0.0s
[CV 5/5] END ..C=0.01, gamma=scale, kernel=poly;, score=0.051 total time=   0.0s
[CV 1/5] END C=0.01, gamma=scale, kernel=sigmoid;, score=-0.167 total time=   0.0s
[CV 2/5] END C=0.01, gamma=scale, kernel=sigmoid;, score=-0.042 total time=   0.0s
[CV 3/5] END C=0.01, gamma=scale, kernel=sigmoid;, score=-0.035 total time=   0.0s
[CV 4/5] END C=0.01, gamma=scale, kernel=sigmoid;, score=-0.041 total time=   0.0s
[CV 5/5] END C=0.01, gamma=scale, kernel=sigmoid;, score=-0.169 total time=   0.0s
[CV 1/5] END .C=0.01, gamma=auto, kernel=linear;, score=0.079 total time=   0.0s
[CV 2/5] END .C=0.01, gamma=auto, kernel=linear;, score=0.262 total time=   0.0s
[CV 3/5] END .C=0.01, gamma=auto, kernel=linear;, score=0.177 total time=   0.0s
[CV 4/5] END .C=0.01, gamma=auto, kernel=linear;, score=0.277 total time=   0.0s
[CV 5/5] END .C=0.01, gamma=auto, kernel=linear;, score=0.020 total time=   0.0s
[CV 1/5] END ...C=0.01, gamma=auto, kernel=rbf;, score=-0.136 total time=   0.0s
[CV 2/5] END ...C=0.01, gamma=auto, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 3/5] END ...C=0.01, gamma=auto, kernel=rbf;, score=-0.021 total time=   0.0s
[CV 4/5] END ...C=0.01, gamma=auto, kernel=rbf;, score=-0.022 total time=   0.0s
[CV 5/5] END ...C=0.01, gamma=auto, kernel=rbf;, score=-0.147 total time=   0.0s
[CV 1/5] END ...C=0.01, gamma=auto, kernel=poly;, score=0.267 total time=   0.0s
[CV 2/5] END ...C=0.01, gamma=auto, kernel=poly;, score=0.589 total time=   0.0s
[CV 3/5] END ...C=0.01, gamma=auto, kernel=poly;, score=0.301 total time=   0.0s
[CV 4/5] END ...C=0.01, gamma=auto, kernel=poly;, score=0.642 total time=   0.0s
[CV 5/5] END ...C=0.01, gamma=auto, kernel=poly;, score=0.129 total time=   0.0s
[CV 1/5] END C=0.01, gamma=auto, kernel=sigmoid;, score=-0.167 total time=   0.0s
[CV 2/5] END C=0.01, gamma=auto, kernel=sigmoid;, score=-0.042 total time=   0.0s
[CV 3/5] END C=0.01, gamma=auto, kernel=sigmoid;, score=-0.035 total time=   0.0s
[CV 4/5] END C=0.01, gamma=auto, kernel=sigmoid;, score=-0.040 total time=   0.0s
[CV 5/5] END C=0.01, gamma=auto, kernel=sigmoid;, score=-0.169 total time=   0.0s

GridSearchCV(cv=5, estimator=SVR(),
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf', 'poly', 'sigmoid']},
             verbose=3)

In [183]:
grid.best_params_

{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}

In [184]:
grid_predict = grid.predict(x_test)
print(r2_score(y_test,grid_predict))
print(mean_absolute_error(y_test,grid_predict))

0.5921426223596538
4.1731609906016995